### ISSUE TITLE
Xtext 2.17 End Game

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1397]
This Issue describes what needs to be done for the Xtext 2.17 release 2019-03-05

- [x] Fix Orbit issue https://github.com/eclipse/xtext-umbrella/issues/104
- [x] test, test, test even more
- [x] regularly run eclipse and xtend jobs against "latest"
- [x] track new Orbit Milestones and Release Candidates and update the p2 composite accordingly (see https://github.com/xtext/xtext-p2-orbit/pull/12 for an example)
       see https://github.com/xtext/xtext-p2-orbit/pull/14
- [x] watch release review https://bugs.eclipse.org/bugs/show_bug.cgi?id=544136 / https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18980 (IP Log :ok: , Modeling PMC :ok:)
- [x] update to Gradle 5.2.1 https://github.com/eclipse/xtext/issues/1393 (Blocked by CQ http://dev.eclipse.org/ipzilla/show_bug.cgi?id=18944), PRs are open
- [x] release and update to MWE 2.10 https://github.com/eclipse/xtext/issues/1283, PRs are open, need to be rerun, (waiting for jcenter sync happening)
- [x] when mwe and gradle are done: recreate reference projects (+ add java 11 testcases)
- [x] document BOM https://github.com/eclipse/xtext/issues/1385
- [x] write release notes https://github.com/eclipse/xtext/issues/1353
  - [x] BOM
  - [x] Static Favorites https://github.com/eclipse/xtext/issues/1402
  - [x] Class name validation in Xtend (Abstract..)
  - [x] ...
- [x] Regenerate Docs
- [x] Regenerate (Test) Languages
 (+ maybe document how)
- [x] Mergable Manifest Problem: https://github.com/eclipse/xtext-core/issues/1038

https://github.com/search?utf8=%E2%9C%93&q=is%3Aissue+milestone%3ARelease_2.17+is%3Aopen+repo%3Aeclipse%2Fxtext+repo%3Aeclipse%2Fxtext-umbrella+repo%3Aeclipse%2Fxtext-core+repo%3Aeclipse%2Fxtext-lib+repo%3Aeclipse%2Fxtext-extras+repo%3Aeclipse%2Fxtext-eclipse+repo%3Aeclipse%2Fxtext-web+repo%3Aeclipse%2Fxtext-maven+repo%3Aeclipse%2Fxtext-xtend&type=Issues&ref=searchresults

**Comment by szarnekow** [comment]
cc @epoell

**Comment by cdietrich** [comment]
done
