### ISSUE TITLE
[2020-06] Simrel Tasks

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1680]
This is an Umbrella for the 2020-06 Simrel Tasks

- [x] Bump Versions on master https://github.com/eclipse/xtext/issues/1688
- [x] Bootstrapping https://github.com/eclipse/xtext/issues/1687
- [x] Update Oomph https://github.com/eclipse/xtext/issues/1681
- [x] Update Orbit https://github.com/eclipse/xtext/issues/1682
- [x] Api Diff Job https://github.com/eclipse/xtext/issues/1683
- [x] Reference Projects https://github.com/eclipse/xtext/issues/1684
- [x] latest target platforms / 2020-03 ibuilds https://github.com/eclipse/xtext/issues/1685
- [x] r202003 target platform https://github.com/eclipse/xtext/issues/1686
- [x] create release notes https://github.com/eclipse/xtext/issues/1689
- [x] adapt docs https://github.com/eclipse/xtext/issues/1696

also track if something is missing here or improperly documented

**Comment by Hejado** [comment]
We might let sign-and-deploy create those issues after a successful full release. WDYT?

**Comment by cdietrich** [comment]
i am not sure if this would be overautomation

**Comment by Hejado** [comment]
> overautomation

There is no such thing. :-)

**Comment by kthoms** [comment]
I like the idea. We already know how to use the GitHub REST API automatically (see bot-updates job). If you could manage this would be great.

**Comment by cdietrich** [comment]
done
