### ISSUE TITLE
[2020-09] Simrel Tasks

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1788]
This is an Umbrella for the 2020-09 Simrel Tasks

- [x] Bump Versions on master https://github.com/eclipse/xtext/issues/1778
- [x] Bootstrapping https://github.com/eclipse/xtext/issues/1779
- [x] Update Oomph https://github.com/eclipse/xtext/issues/1780
- [x] Update Orbit https://github.com/eclipse/xtext/issues/1781
- [x] Api Diff Job https://github.com/eclipse/xtext/issues/1782
- [x] Reference Projects https://github.com/eclipse/xtext/issues/1783
- [x] latest target platforms / 2020-09 ibuilds https://github.com/eclipse/xtext/issues/1784
- [x] r202006 target platform https://github.com/eclipse/xtext/issues/1785
- [ ] create release notes https://github.com/eclipse/xtext/issues/1786
- [x] adapt docs https://github.com/eclipse/xtext/issues/1787

also track if something is missing here or improperly documented
