### ISSUE TITLE
[2020-12] Simrel Tasks

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1835]
This is an Umbrella for the 2020-12 Simrel Tasks

- [x] Bump Versions on master https://github.com/eclipse/xtext/issues/1825
- [x] Bootstrapping https://github.com/eclipse/xtext/issues/1826
- [x] Update Oomph https://github.com/eclipse/xtext/issues/1827
- [x] Update Orbit https://github.com/eclipse/xtext/issues/1828
- [x] Api Diff Job https://github.com/eclipse/xtext/issues/1829
- [x] Reference Projects https://github.com/eclipse/xtext/issues/1830
- [x] latest target platforms / 2020-12 ibuilds https://github.com/eclipse/xtext/issues/1831
- [x] r202009 target https://github.com/eclipse/xtext/issues/1832
- [x] create release notes https://github.com/eclipse/xtext/issues/1833
- [x] adapt docs https://github.com/eclipse/xtext/issues/1834

also track if something is missing here or improperly documented

**Comment by cdietrich** [comment]
done
