### ISSUE TITLE
[2021-03] Simrel Tasks

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1889]
This is an Umbrella for the 2021-03 Simrel Tasks

- [x] Bump Versions on master https://github.com/eclipse/xtext/issues/1879
- [x] Bootstrapping https://github.com/eclipse/xtext/issues/1880
- [x] Update Oomph https://github.com/eclipse/xtext/issues/1881
- [x] Update Orbit https://github.com/eclipse/xtext/issues/1882
- [x] Api Diff Job https://github.com/eclipse/xtext/issues/1883
- [x] Reference Projects https://github.com/eclipse/xtext/issues/1884
- [x] latest target platforms / 2021-03 ibuilds https://github.com/eclipse/xtext/issues/1885
- [x] r202012 target https://github.com/eclipse/xtext/issues/1886
- [x] create release notes https://github.com/eclipse/xtext/issues/1887
- [x] adapt docs https://github.com/eclipse/xtext/issues/1888
- [x] release review https://github.com/eclipse/xtext/issues/1890

also track if something is missing here or improperly documented

**Comment by cdietrich** [comment]
release review also done

**Comment by cdietrich** [comment]
done
