### ISSUE TITLE
[2021-06] Adaptation Tasks

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1951]
This is an Umbrella for the 2021-06 Adaptation Tasks

- [x] Bump Versions on master https://github.com/eclipse/xtext/issues/1941
- [x] Bootstrapping https://github.com/eclipse/xtext/issues/1942
- [x] Update Oomph https://github.com/eclipse/xtext/issues/1943
- [x] Update Orbit https://github.com/eclipse/xtext/issues/1944
- [x] Api Diff Job https://github.com/eclipse/xtext/issues/1945
- [x] Reference Projects https://github.com/eclipse/xtext/issues/1946
- [x] latest target platforms / 2021-06 ibuilds https://github.com/eclipse/xtext/issues/1947
- [x] r202103 target https://github.com/eclipse/xtext/issues/1948
- [ ] create release notes https://github.com/eclipse/xtext/issues/1949
- [x] adapt docs https://github.com/eclipse/xtext/issues/1950

also track if something is missing here or improperly documented

**Comment by cdietrich** [comment]
as we are out of simrel no longer relevant
