### ISSUE TITLE
Java 17 Masterplan

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1982]
This is a collection of issues and thing needed to get Java 17 support

- [x] Guice 5 Update https://github.com/eclipse/xtext-core/issues/393
- [x] Gradle Update (This affects the build of Xtext itself and the stuff we create in the wizard https://github.com/eclipse/xtext-core/issues/1726 https://github.com/eclipse/xtext/issues/1548 . We also dont have a way to have the gwt stuff with newer gradle. Maybe replace the gradle stuff with tycho and create maven artifacts after the fact as emf and platform do. **I REALLY NEED HELP HERE**
- [x] Xbase has problems with newer JDK classes https://github.com/eclipse/xtext-extras/issues/704
- [x] Newer platform artifacts dont support Java 8 anymore, but we need them to deal with Java 17 https://github.com/eclipse/xtext/issues/1915 https://github.com/eclipse/xtext/issues/1972 https://github.com/eclipse/xtext/issues/1804
- [x] Java Version enum and ASTParserFactory need adaption (consider changing minParserApiLevel to 11 and asJLS default to 11, too)
- [x] New Tycho version needed.
- [x] We also should have a solution for the transitive deps stuff https://github.com/eclipse/xtext/issues/1976 https://github.com/eclipse/xtext-maven/issues/146
- [x] do we need new classgraph https://github.com/eclipse/xtext/issues/2098 /asm? (for classgraph test if https://github.com/eclipse/xtext/issues/1992 will be sufficient)
- [x] delete tests for old merableManifest or the class itself https://github.com/eclipse/xtext-core/issues/1744
- [x] fix org.eclipse.xtext.common.types.access.reflect.ReflectionTypeProviderTest & co https://github.com/eclipse/xtext-extras/issues/723
- [x] Fix Xtend / Xbase  CA Tests https://github.com/eclipse/xtext-xtend/issues/1226 https://github.com/eclipse/xtext-eclipse/issues/1725
- [x] Update from Gradle 7.1 to Gradle 7.2+
- [x] Update to Gradle 7.3 for better Java 17 Support
- [x] Release MWE and Bootstrap against it https://github.com/eclipse/xtext/issues/2106 https://github.com/eclipse/xtext/issues/2107
- [x] Update platform artifacts (will require minimum Java 11 to run)
- [x] https://github.com/eclipse/xtext/issues/1995
- [x] https://github.com/eclipse/xtext-web/issues/309
- [x] https://github.com/eclipse/xtext/issues/2002 (will allow to run nightly with 17)
- [x] https://github.com/eclipse/xtext/issues/2003
- [x] https://github.com/eclipse/xtext/issues/2007
- [x] https://github.com/eclipse/xtext-xtend/issues/1268
- [x] Use consistent tycho version across all repos (2.7.4?)
- [x] https://github.com/eclipse/xtext-xtend/issues/1382
- [x] cleanup switches in tests
- [x] grgit gradle bump

see also https://github.com/eclipse/xtext/issues/1974

Many more unknown tasks and issues.

Work in progress maven repos can be found at
https://ci.eclipse.org/xtext/job/xtext-lib/job/cd_platformUpdateExp/lastSuccessfulBuild/artifact/build/maven-repository/
https://ci.eclipse.org/xtext/job/xtext-core/job/cd_platformUpdateExp/lastSuccessfulBuild/artifact/build/maven-repository/
https://ci.eclipse.org/xtext/job/xtext-extras/job/cd_platformUpdateExp/lastSuccessfulBuild/artifact/build/maven-repository/
https://ci.eclipse.org/xtext/job/xtext-xtend/job/cd_platformUpdateExp/lastSuccessfulBuild/artifact/build/maven-repository/
https://ci.eclipse.org/xtext/job/xtext-maven/job/cd_platformUpdateExp/lastSuccessfulBuild/artifact/build/maven-repository/
https://ci.eclipse.org/xtext/job/xtext-web/job/cd_platformUpdateExp/lastSuccessfulBuild/artifact/build/maven-repository/

and a p2 repo at
https://ci.eclipse.org/xtext/job/xtext-umbrella/job/cd_platformUpdateExp/lastSuccessfulBuild/artifact/build/p2-repository

**Comment by cdietrich** [comment]
Hi all, 

I am pleased to announce the availability of Xtext 2.26.0.M2.
This is the first version that won't explode with Java 17 thanks to an update to Google Guice 5.0
(run with Java 17 against 8/11 target, running against 17 will follow next year when platform/jdt and other upstream dependencies also support it)
We also did some changes to how recovery builds are scheduled https://github.com/eclipse/xtext-eclipse/issues/1710

Release Notes (WIP) are at https://github.com/eclipse/xtext/blob/website-master/xtext-website/_posts/releasenotes/2021-12-31-version-2-26-0.md

For both we strongly encourage you to test and give feedback.

You can find the milestone at https://download.eclipse.org/modeling/tmf/xtext/updates/milestones/S202110010541/
and http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/drops/2.26.0/S202110010541/tmf-xtext-Update-2.26.0.M2.zip
and soon on Maven Central

Happy Xtexting

Thanks and Regards
Christian

**Comment by cdietrich** [comment]
thx i fixed the post.

**Comment by cdietrich** [comment]
the current plan is to release this in two parts.
- part 1 is: do not explode with Java 17 against 8 and 11 runtime with 2.26
- part 2 is: support java 17 runtime, drop support for 8 runtime 2.27

**Comment by cdietrich** [comment]
part 1 is done. will move part 2 to 2.27.0

**Comment by wborn** [comment]
> For both we strongly encourage you to test and give feedback.

I did some testing with 2.26.0.M3 today with openHAB on Java 17 (https://github.com/openhab/openhab-core/pull/2786) and I it all worked very well. :+1: Also nice to see LSP4J is upgraded so everything uses the same Guava dependency. :slightly_smiling_face:

**Comment by wborn** [comment]
Upgrading to Gson 2.9.0 also seems to improve Java 17 support. I tried to build openHAB with Java 17 and some tests failed which seems to be fixed in Gson 2.9.0 as it has "Fix failing to serialize Collection or Map with inaccessible constructor" (see [Gson 2.9.0 release notes](https://github.com/google/gson/releases/tag/gson-parent-2.9.0)).

**Comment by cdietrich** [comment]
Java 17 Supported moved to 2.28

**Comment by cdietrich** [comment]
due to lack of capacity we will move this to 2.29

**Comment by cdietrich** [comment]
Work in progress maven repos can be found at
https://ci.eclipse.org/xtext/job/xtext-lib/job/cd_platformUpdateExp/lastSuccessfulBuild/artifact/build/maven-repository/
https://ci.eclipse.org/xtext/job/xtext-core/job/cd_platformUpdateExp/lastSuccessfulBuild/artifact/build/maven-repository/
https://ci.eclipse.org/xtext/job/xtext-extras/job/cd_platformUpdateExp/lastSuccessfulBuild/artifact/build/maven-repository/
https://ci.eclipse.org/xtext/job/xtext-xtend/job/cd_platformUpdateExp/lastSuccessfulBuild/artifact/build/maven-repository/
https://ci.eclipse.org/xtext/job/xtext-maven/job/cd_platformUpdateExp/lastSuccessfulBuild/artifact/build/maven-repository/
https://ci.eclipse.org/xtext/job/xtext-web/job/cd_platformUpdateExp/lastSuccessfulBuild/artifact/build/maven-repository/

and a p2 repo at
https://ci.eclipse.org/xtext/job/xtext-umbrella/job/cd_platformUpdateExp/lastSuccessfulBuild/artifact/build/p2-repository

feedback is welcome

**Comment by cdietrich** [comment]
TODO: set minimal target to 2022-03, adapt platform maven artifacts to that one too. (or can we use 2022-09 there?!?)

**Comment by cdietrich** [comment]
please test and give feedback

**Comment by cdietrich** [comment]
looks like we are going to deliver this as is in 2.29 and will do further enhancements in 2.30

**Comment by cdietrich** [comment]
created https://github.com/eclipse/xtext/issues/2115 for leftovers

**Comment by cdietrich** [comment]
part I, done
